//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EricWoodsPhotography.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbum
    {
        public int AlbumId { get; set; }
        public string UserId { get; set; }
        public int PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
